pipeline edited

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -10,61 +10,35 @@ image:
   name: hashicorp/terraform:1.10
   entrypoint: [""]
 
+variables:
+  AWS_DEFAULT_REGION: "us-east-1"
+
+before_script:
+  - export AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
+  - export AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
+
 statelock:
-  id_tokens:
-    GITLAB_OIDC_TOKEN:
-      aud: https://gitlab.com
   stage: dynamodb
   image: 
     name: amazon/aws-cli:latest
     entrypoint: [""]
-  before_script:
-  # Establish connection with AWS to get access credentials
-    - >
-      export $(printf "AWS_ACCESS_KEY_ID=%s AWS_SECRET_ACCESS_KEY=%s AWS_SESSION_TOKEN=%s"
-      $(aws sts assume-role-with-web-identity
-      --role-arn ${ROLE_ARN}
-      --role-session-name "GitLabRunner-${CI_PROJECT_ID}-${CI_PIPELINE_ID}"
-      --web-identity-token ${GITLAB_OIDC_TOKEN}
-      --duration-seconds 3600
-      --query 'Credentials.[AccessKeyId,SecretAccessKey,SessionToken]'
-      --output text))
   script:
-      # Check if the DynamoDB table already exists
-    - aws configure set region eu-west-2
     - |
-      TABLE_EXISTS=$(aws dynamodb describe-table --table-name tfstate-dynamo-lock 2>&1 || echo "not found")
+      TABLE_EXISTS=$(aws dynamodb describe-table --table-name ng-java-app-terraform-lock --region us-east-1 2>&1 || echo "not found")
       if [[ "$TABLE_EXISTS" == *"not found"* ]]; then
-        echo "Table does not exist, creating it..."
+        echo "Creating DynamoDB table ng-java-app-terraform-lock..."
         aws dynamodb create-table \
-          --table-name tfstate-dynamo-lock \
+          --table-name ng-java-app-terraform-lock \
           --attribute-definitions AttributeName=LockID,AttributeType=S \
           --key-schema AttributeName=LockID,KeyType=HASH \
-          --provisioned-throughput ReadCapacityUnits=5,WriteCapacityUnits=5
+          --provisioned-throughput ReadCapacityUnits=5,WriteCapacityUnits=5 \
+          --region us-east-1
       else
         echo "Table already exists, skipping creation."
       fi
       
 init:
-  id_tokens:
-    GITLAB_OIDC_TOKEN:
-      aud: https://gitlab.com
   stage: init
-  before_script:
-  # Install AWS CLI
-    - apk --no-cache add curl python3 py3-pip
-    - pip3 install --no-cache-dir awscli --break-system-packages
-  
-  # Establish connection with AWS to get access credentials
-    - >
-      export $(printf "AWS_ACCESS_KEY_ID=%s AWS_SECRET_ACCESS_KEY=%s AWS_SESSION_TOKEN=%s"
-      $(aws sts assume-role-with-web-identity
-      --role-arn ${ROLE_ARN}
-      --role-session-name "GitLabRunner-${CI_PROJECT_ID}-${CI_PIPELINE_ID}"
-      --web-identity-token ${GITLAB_OIDC_TOKEN}
-      --duration-seconds 3600
-      --query 'Credentials.[AccessKeyId,SecretAccessKey,SessionToken]'
-      --output text))
   script:
     - terraform init 
   artifacts:
@@ -73,51 +47,19 @@ init:
       - .terraform.lock.hcl
 
 validate:
-  id_tokens:
-    GITLAB_OIDC_TOKEN:
-      aud: https://gitlab.com
   stage: validate
-  before_script:
-  # Install AWS CLI
-    - apk --no-cache add curl python3 py3-pip
-    - pip3 install --no-cache-dir awscli --break-system-packages
-  
-  # Establish connection with AWS to get access credentials
-    - >
-      export $(printf "AWS_ACCESS_KEY_ID=%s AWS_SECRET_ACCESS_KEY=%s AWS_SESSION_TOKEN=%s"
-      $(aws sts assume-role-with-web-identity
-      --role-arn ${ROLE_ARN}
-      --role-session-name "GitLabRunner-${CI_PROJECT_ID}-${CI_PIPELINE_ID}"
-      --web-identity-token ${GITLAB_OIDC_TOKEN}
-      --duration-seconds 3600
-      --query 'Credentials.[AccessKeyId,SecretAccessKey,SessionToken]'
-      --output text))
+  dependencies:
+    - init
   script:
     - terraform fmt -check -recursive
     - terraform validate
 
 plan:
-  id_tokens:
-    GITLAB_OIDC_TOKEN:
-      aud: https://gitlab.com
   stage: plan
-  before_script:
-  # Install AWS CLI
-    - apk --no-cache add curl python3 py3-pip
-    - pip3 install --no-cache-dir awscli --break-system-packages
-  
-  # Establish connection with AWS to get access credentials
-    - >
-      export $(printf "AWS_ACCESS_KEY_ID=%s AWS_SECRET_ACCESS_KEY=%s AWS_SESSION_TOKEN=%s"
-      $(aws sts assume-role-with-web-identity
-      --role-arn ${ROLE_ARN}
-      --role-session-name "GitLabRunner-${CI_PROJECT_ID}-${CI_PIPELINE_ID}"
-      --web-identity-token ${GITLAB_OIDC_TOKEN}
-      --duration-seconds 3600
-      --query 'Credentials.[AccessKeyId,SecretAccessKey,SessionToken]'
-      --output text))
+  dependencies:
+    - init
   script:
-    - terraform plan -out "planfile"
+    - terraform plan -var-file=staging.tfvars -out=planfile
     - terraform show -no-color planfile > planfile.txt
   artifacts:
     paths:
@@ -127,55 +69,25 @@ plan:
       terraform: planfile
 
 apply:
-  id_tokens:
-    GITLAB_OIDC_TOKEN:
-      aud: https://gitlab.com
   stage: apply
-  before_script:
-  # Install AWS CLI
-    - apk --no-cache add curl python3 py3-pip
-    - pip3 install --no-cache-dir awscli --break-system-packages
-  
-  # Establish connection with AWS to get access credentials
-    - >
-      export $(printf "AWS_ACCESS_KEY_ID=%s AWS_SECRET_ACCESS_KEY=%s AWS_SESSION_TOKEN=%s"
-      $(aws sts assume-role-with-web-identity
-      --role-arn ${ROLE_ARN}
-      --role-session-name "GitLabRunner-${CI_PROJECT_ID}-${CI_PIPELINE_ID}"
-      --web-identity-token ${GITLAB_OIDC_TOKEN}
-      --duration-seconds 3600
-      --query 'Credentials.[AccessKeyId,SecretAccessKey,SessionToken]'
-      --output text))
+  dependencies:
+    - plan
   script:
-    - terraform apply -input=false "planfile"
+    - terraform apply -input=false planfile
     - terraform output > output.txt
   artifacts:
     paths:
       - output.txt
-    reports:
-      terraform: output.txt
   when: manual
 
 destroy:
-  id_tokens:
-    GITLAB_OIDC_TOKEN:
-      aud: https://gitlab.com
   stage: destroy
-  before_script:
-  # Install AWS CLI
-    - apk --no-cache add curl python3 py3-pip
-    - pip3 install --no-cache-dir awscli --break-system-packages
-  
-  # Establish connection with AWS to get access credentials
-    - >
-      export $(printf "AWS_ACCESS_KEY_ID=%s AWS_SECRET_ACCESS_KEY=%s AWS_SESSION_TOKEN=%s"
-      $(aws sts assume-role-with-web-identity
-      --role-arn ${ROLE_ARN}
-      --role-session-name "GitLabRunner-${CI_PROJECT_ID}-${CI_PIPELINE_ID}"
-      --web-identity-token ${GITLAB_OIDC_TOKEN}
-      --duration-seconds 3600
-      --query 'Credentials.[AccessKeyId,SecretAccessKey,SessionToken]'
-      --output text))
+  dependencies:
+    - init
   script:
-    - terraform destroy --auto-approve
+    - terraform destroy -var-file=staging.tfvars --auto-approve | tee destroy-output.txt
+  artifacts:
+    paths:
+      - destroy-output.txt
+    expire_in: 7 days
   when: manual
